version: "3.9"
services:
  postgres-account:
    image: "postgres:alpine"
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    #   Set a volume for data and initial sql script.
    #   May configure initial db for future demo.
    volumes:
      - "pgdata_account:/var/lib/postgresql/data"
      # - ./init:/docker-entrypoint-initdb.d/
    command: ["postgres", "-c", "log_statement=all"]
  redis-account:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - "redisdata:/data"
  account:
    build:
      context: ./account
      target: builder
    image: account
    env_file: ./account/.env.dev
    ports:
      - "8080:8080"
    environment:
      - ENV=dev
    volumes:
      - ./account:/go/src/app
    # Have to use $$ (double-dollar) so docker does not try to substitute a variable.
    depends_on:
      - postgres-account
      - redis-account
    command: reflex -r "\.go$$" -s -- sh -c "go run ./"
volumes:
  pgdata_account:
  redisdata: 